import type { SourceRef } from "@/lib/types";

export function Footer({ sources }: { sources: SourceRef[]; }) {
  return (
    <footer className="border-t-2 border-lilac bg-cream">
      <div className="mx-auto max-w-3xl px-6 py-12">
        <h3 className="font-display text-lg font-bold">Sources</h3>
        <ul className="mt-3 space-y-1.5 text-sm">
          {sources.map((s, i) => (
            <li key={i}>
              <a
                href={s.url ?? "#"}
                target="_blank"
                rel="noreferrer"
                className="text-purple hover:underline"
              >
                {s.title || s.url}
              </a>
              {s.outlet && <span className="text-ink/50"> — {s.outlet}</span>}
            </li>
          ))}
        </ul>
        <p className="mt-8 text-xs text-ink/50">
          Auto-generated by the NBT blog post pipeline
        </p>
      </div>
    </footer>
  );
}
